# Dependency resolution: system / vcpkg packages first, FetchContent as a fallback.
include(FetchContent)
find_package(Threads REQUIRED)
set(RX_DEP_LIBS "")
set(RX_DEP_DEFS "")

# ---- meshoptimizer (required) --------------------------------------------------------
find_package(meshoptimizer CONFIG QUIET)
if(meshoptimizer_FOUND)
  list(APPEND RX_DEP_LIBS meshoptimizer::meshoptimizer)
elseif(RX_FETCH_DEPS)
  FetchContent_Declare(meshoptimizer GIT_REPOSITORY https://github.com/zeux/meshoptimizer.git GIT_TAG v0.22 GIT_SHALLOW TRUE)
  FetchContent_MakeAvailable(meshoptimizer)
  list(APPEND RX_DEP_LIBS meshoptimizer)
else()
  message(FATAL_ERROR "meshoptimizer not found")
endif()

# ---- nlohmann_json (required, header only) -------------------------------------------
find_package(nlohmann_json 3.9 CONFIG QUIET)
if(nlohmann_json_FOUND)
  list(APPEND RX_DEP_LIBS nlohmann_json::nlohmann_json)
elseif(RX_FETCH_DEPS)
  FetchContent_Declare(json URL https://github.com/nlohmann/json/releases/download/v3.11.3/json.tar.xz)
  FetchContent_MakeAvailable(json)
  list(APPEND RX_DEP_LIBS nlohmann_json::nlohmann_json)
else()
  message(FATAL_ERROR "nlohmann_json not found")
endif()

# ---- stb (required, header only; included as <stb/stb_image.h>) ----------------------
find_path(RX_STB_INCLUDE stb/stb_image.h)
if(NOT RX_STB_INCLUDE)
  find_path(RX_STB_FLAT stb_image.h PATH_SUFFIXES stb)
  if(NOT RX_STB_FLAT AND RX_FETCH_DEPS)
    FetchContent_Declare(stb GIT_REPOSITORY https://github.com/nothings/stb.git GIT_TAG master GIT_SHALLOW TRUE)
    FetchContent_MakeAvailable(stb)
    set(RX_STB_FLAT ${stb_SOURCE_DIR})
  endif()
  if(NOT RX_STB_FLAT)
    message(FATAL_ERROR "stb headers not found")
  endif()
  set(RX_STB_INCLUDE ${CMAKE_BINARY_DIR}/stb_wrap)
  file(MAKE_DIRECTORY ${RX_STB_INCLUDE}/stb)
  foreach(h stb_image.h stb_image_write.h stb_rect_pack.h)
    configure_file(${RX_STB_FLAT}/${h} ${RX_STB_INCLUDE}/stb/${h} COPYONLY)
  endforeach()
endif()

# ---- libwebp (strongly recommended: WebP textures are the default) ---------------------
find_package(WebP CONFIG QUIET)
if(WebP_FOUND)
  list(APPEND RX_DEP_LIBS WebP::webp WebP::webpdecoder)
  set(RX_HAVE_WEBP ON)
else()
  find_package(PkgConfig QUIET)
  if(PkgConfig_FOUND)
    pkg_check_modules(WEBP IMPORTED_TARGET libwebp)
  endif()
  if(WEBP_FOUND)
    list(APPEND RX_DEP_LIBS PkgConfig::WEBP)
    set(RX_HAVE_WEBP ON)
  elseif(RX_FETCH_DEPS)
    set(WEBP_BUILD_ANIM_UTILS OFF CACHE BOOL "" FORCE)
    set(WEBP_BUILD_CWEBP OFF CACHE BOOL "" FORCE)
    set(WEBP_BUILD_DWEBP OFF CACHE BOOL "" FORCE)
    set(WEBP_BUILD_GIF2WEBP OFF CACHE BOOL "" FORCE)
    set(WEBP_BUILD_IMG2WEBP OFF CACHE BOOL "" FORCE)
    set(WEBP_BUILD_VWEBP OFF CACHE BOOL "" FORCE)
    set(WEBP_BUILD_WEBPINFO OFF CACHE BOOL "" FORCE)
    set(WEBP_BUILD_WEBPMUX OFF CACHE BOOL "" FORCE)
    set(WEBP_BUILD_EXTRAS OFF CACHE BOOL "" FORCE)
    FetchContent_Declare(libwebp GIT_REPOSITORY https://github.com/webmproject/libwebp.git GIT_TAG v1.4.0 GIT_SHALLOW TRUE)
    FetchContent_MakeAvailable(libwebp)
    list(APPEND RX_DEP_LIBS webp webpdecoder)
    set(RX_HAVE_WEBP ON)
  else()
    message(WARNING "libwebp not found: WebP textures disabled (PNG will be used)")
    set(RX_HAVE_WEBP OFF)
  endif()
endif()
if(RX_HAVE_WEBP)
  list(APPEND RX_DEP_DEFS RX_HAVE_WEBP)
endif()

# ---- zlib (optional: better PNG compression) ------------------------------------------
find_package(ZLIB QUIET)
if(ZLIB_FOUND)
  list(APPEND RX_DEP_LIBS ZLIB::ZLIB)
  list(APPEND RX_DEP_DEFS RX_HAVE_ZLIB)
  set(RX_HAVE_ZLIB ON)
endif()

# ---- oneTBB (optional) ------------------------------------------------------------------
set(RX_HAVE_TBB OFF)
if(RX_WITH_TBB)
  find_package(TBB CONFIG QUIET)
  if(TBB_FOUND)
    list(APPEND RX_DEP_LIBS TBB::tbb)
    list(APPEND RX_DEP_DEFS RX_HAVE_TBB)
    set(RX_HAVE_TBB ON)
  endif()
endif()

# ---- Assimp (optional but recommended: 40+ formats) ---------------------------------------
set(RX_HAVE_ASSIMP OFF)
if(RX_WITH_ASSIMP)
  find_package(assimp CONFIG QUIET)
  if(assimp_FOUND)
    if(TARGET assimp::assimp)
      list(APPEND RX_DEP_LIBS assimp::assimp)
    else()
      list(APPEND RX_DEP_LIBS ${ASSIMP_LIBRARIES})
    endif()
    set(RX_HAVE_ASSIMP ON)
  elseif(RX_FETCH_DEPS)
    set(ASSIMP_BUILD_TESTS OFF CACHE BOOL "" FORCE)
    set(ASSIMP_BUILD_ASSIMP_TOOLS OFF CACHE BOOL "" FORCE)
    set(ASSIMP_INSTALL OFF CACHE BOOL "" FORCE)
    set(ASSIMP_WARNINGS_AS_ERRORS OFF CACHE BOOL "" FORCE)
    set(BUILD_SHARED_LIBS OFF CACHE BOOL "" FORCE)
    FetchContent_Declare(assimp GIT_REPOSITORY https://github.com/assimp/assimp.git GIT_TAG v5.4.3 GIT_SHALLOW TRUE)
    FetchContent_MakeAvailable(assimp)
    list(APPEND RX_DEP_LIBS assimp)
    set(RX_HAVE_ASSIMP ON)
  endif()
  if(RX_HAVE_ASSIMP)
    list(APPEND RX_DEP_DEFS RX_HAVE_ASSIMP)
  endif()
endif()

# ---- Draco (optional: KHR_draco_mesh_compression input) -----------------------------------
set(RX_HAVE_DRACO OFF)
if(RX_WITH_DRACO)
  find_package(draco CONFIG QUIET)
  if(draco_FOUND)
    if(TARGET draco::draco)
      list(APPEND RX_DEP_LIBS draco::draco)
    elseif(TARGET draco_shared)
      list(APPEND RX_DEP_LIBS draco_shared)
    else()
      list(APPEND RX_DEP_LIBS ${draco_LIBRARIES})
      include_directories(${draco_INCLUDE_DIRS})
    endif()
    list(APPEND RX_DEP_DEFS RX_HAVE_DRACO)
    set(RX_HAVE_DRACO ON)
  endif()
endif()
